/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ShowsIndexRouteImport } from "./routes/shows/index";
import { Route as BrowseShowsIndexRouteImport } from "./routes/browse/shows/index";
import { Route as BrowseMoviesIndexRouteImport } from "./routes/browse/movies/index";

const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any);
const ShowsIndexRoute = ShowsIndexRouteImport.update({
    id: "/shows/",
    path: "/shows/",
    getParentRoute: () => rootRouteImport,
} as any);
const BrowseShowsIndexRoute = BrowseShowsIndexRouteImport.update({
    id: "/browse/shows/",
    path: "/browse/shows/",
    getParentRoute: () => rootRouteImport,
} as any);
const BrowseMoviesIndexRoute = BrowseMoviesIndexRouteImport.update({
    id: "/browse/movies/",
    path: "/browse/movies/",
    getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/shows": typeof ShowsIndexRoute;
    "/browse/movies": typeof BrowseMoviesIndexRoute;
    "/browse/shows": typeof BrowseShowsIndexRoute;
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/shows": typeof ShowsIndexRoute;
    "/browse/movies": typeof BrowseMoviesIndexRoute;
    "/browse/shows": typeof BrowseShowsIndexRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    "/": typeof IndexRoute;
    "/shows/": typeof ShowsIndexRoute;
    "/browse/movies/": typeof BrowseMoviesIndexRoute;
    "/browse/shows/": typeof BrowseShowsIndexRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/shows" | "/browse/movies" | "/browse/shows";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/shows" | "/browse/movies" | "/browse/shows";
    id: "__root__" | "/" | "/shows/" | "/browse/movies/" | "/browse/shows/";
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    ShowsIndexRoute: typeof ShowsIndexRoute;
    BrowseMoviesIndexRoute: typeof BrowseMoviesIndexRoute;
    BrowseShowsIndexRoute: typeof BrowseShowsIndexRoute;
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/shows/": {
            id: "/shows/";
            path: "/shows";
            fullPath: "/shows";
            preLoaderRoute: typeof ShowsIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/browse/shows/": {
            id: "/browse/shows/";
            path: "/browse/shows";
            fullPath: "/browse/shows";
            preLoaderRoute: typeof BrowseShowsIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        "/browse/movies/": {
            id: "/browse/movies/";
            path: "/browse/movies";
            fullPath: "/browse/movies";
            preLoaderRoute: typeof BrowseMoviesIndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ShowsIndexRoute: ShowsIndexRoute,
    BrowseMoviesIndexRoute: BrowseMoviesIndexRoute,
    BrowseShowsIndexRoute: BrowseShowsIndexRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
    interface Register {
        ssr: true;
        router: Awaited<ReturnType<typeof getRouter>>;
    }
}
